global:
  rustlog: "debug"
  packages:
    Linux: ""
pages:
  mdbook:
    if: true
release:
  cargo-publish: false
  bin: kg
  debian: true
jobs:
  semver:
    if: false
    continue-on-error: false
  sanitizers:
    enabled: true
    address:
      if: false
      continue-on-error: false

  extra:
    if: true
    continue-on-error: false
    name: "cli test"
    run: |
      cargo build
      export PATH=$PWD/target/debug:$PATH

      kg help
      kg --help
      kg version
      kg --version
      kg validate
      kg v
      kg validate -d
      kg --debug validate
      kg validate --trace dependabot
      kg --trace dependabot validate
      kg v --format json
      kg --format json v
      kg g
      kg generate
      kg init
      kg validate --global

    matrix:
      os: []
      toolchains: ["stable"]
      features: ["default"]
# jobs:
#   coverage:
#     matrix:
#       features:
#         - default
#         - gpg
#   clippy:
#     matrix:
#       features:
#         - default
#         - gpg
