global:
  rustlog: "debug"
  packages:
    Linux: ""
jobs:
  extra:
    if: true
    continue-on-error: false
    name: "cli test"
    run: |
      cargo run -- version
      cargo run -- --version
      cargo run -- validate
      cargo run -- v
      cargo run -- validate -d

    matrix:
      os: []
      toolchains: ["stable"]
      features: ["default"]
# jobs:
#   coverage:
#     matrix:
#       features:
#         - default
#         - gpg
#   clippy:
#     matrix:
#       features:
#         - default
#         - gpg
